### ISSUE TITLE
Find command indexing

### ISSUE THREAD

**Issue by rashthedude** [adobe/brackets.io#45]
The Find tool highlights the amount of found results but doesn't index them e.g. '1 of x'. Would be a cool feature just to see where exactly you are or if you have passed the keyword you were looking for.

**Comment by peterflynn** [comment]
@rashthedude I definitely agree that'd be useful!  We have a [user story in our backlog for this](https://trello.com/c/0GXqt5GF/1089-s-correct-find-next-indicate-current-match-index), and since it's already tracked there I'll close this bug.  Please upvote the user story to indicate it's important to you, and feel free to watch it for updates.

**Comment by peterflynn** [comment]
Also, for future reference -- please file bugs in the [main Brackets repo](https://github.com/adobe/brackets).  This repo is just for the brackets.io website.

**Comment by rashthedude** [comment]
Will certainly do in the future.
