### ISSUE TITLE
Possible Translations?

### ISSUE THREAD

**Issue by ziyaddin** [adobe/brackets.io#90]
Hi, can I translate website content into Azerbaijani language (localization)? Thanks!

**Comment by ingorichter** [comment]
@ziyaddin you are welcome to do so. Let us know if you need any help.

**Comment by marcelgerber** [comment]
@ziyaddin You may take a look at https://github.com/adobe/brackets.io/blob/gh-pages/locales/README.md, which explains how to translate this website.

**Comment by ziyaddin** [comment]
@ingorichter thanks very much! @MarcelGerber thanks for documentation! If I translate, how can I view translated page in website? How can the users change the website language to another one?

**Comment by marcelgerber** [comment]
@ziyaddin After following the steps in the readme (without setting `production` back to `true`), you can view the page via Live Preview. If you're from Azerbaijan, it _should_ use the language automatically, just add `?lang=az` to the URL otherwise.
Others do the same for now, but we might add an option to the site to change the language when more languages are supported.

Ah, and of course you need a `git clone` of the repo in order to edit it.
